### ISSUE TITLE
Missing Data

### ISSUE THREAD

**Issue by patwater** [California-Data-Collaborative/Open-Water-Rate-Specification#491]
As I was adding Melbourne's water rates, I noticed that the data for NY was no longer in the OWRS repo. Same story with EMWD which I thought was included?

**Comment by christophertull** [comment]
Hmmm, I don't recall having NY data but I could just be forgetting. I think we had an issue like 2 years ago merging a local repo with Github and some data was lost in the process. Maybe it disappeared then?

EMWD is tricky. The OWRS file we use in RateComparison is actually a bit customized compared to most of the files we have in the repo so that could be why it is not here.
